# Generated by Django 2.2.4 on 2019-09-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_by_father', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departament', models.ManyToManyField(blank=True, to='student.Departament')),
                ('faculty', models.ManyToManyField(blank=True, default=None, to='student.Faculty')),
                ('group', models.ManyToManyField(blank=True, default=None, to='student.Groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
