# Generated by Django 2.2.4 on 2019-09-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190923_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departament',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
