# Generated by Django 2.2.2 on 2019-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='suffix',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
