# Generated by Django 2.2.2 on 2019-07-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_groups_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='faculty',
        ),
        migrations.AddField(
            model_name='groups',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Faculty'),
        ),
    ]
