# Generated by Django 2.2.2 on 2019-07-29 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0003_auto_20190729_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='User',
        ),
    ]
