# Generated by Django 2.2.2 on 2019-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190801_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='subject',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='main.Subjects'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=None, null=True, to='main.Subjects'),
        ),
    ]
