# Generated by Django 2.2.2 on 2019-08-01 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20190801_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_departament', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('group', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_of_student', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('points', models.IntegerField(blank=True, default=None, null=True)),
                ('redacted_data', models.DateField(auto_now_add=True)),
                ('redacted_by', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_by_father', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('group', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('departament', models.ManyToManyField(blank=True, to='main.Departament')),
                ('faculty', models.ManyToManyField(blank=True, default=None, to='main.Faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
